---
title: "A Tomography of Electoral Methods - Seat Calculator v2.2"
runtime: shiny
output: 
  html_document: 
    fig_height: 9
    fig_width: 9
    keep_md: yes
    toc: yes
---

Explanations and code available here: <http://ismaelsb.github.io/ElectoralSpace> 

Theoretical plots are faster. Simulated plots are slow when density is high. 

Fill in the boxes with the number of votes if you want to compute their allocated seats.

Also try this calculator for multiple parties: <http://ismaelsb.shinyapps.io/SeatCalculator> 

```{r, echo = F, results='hide', message=FALSE, warning=FALSE}
#Uncommmet to install ggtern from an online CRAN repository:
#install.packages("ggtern")
#Load the ggtern library:
library(ggtern)
#library(stats)
set.seed(156) #fix random generation

```

```{r, echo = F}

generateNodes <- function(seats){ 
  
  #define nodes
  nnodes = (seats+1)*(seats+2)/2;
  nodes  = matrix(0,nnodes,3);
  t=1;
  for (i in 0:seats){
    for (j in i:seats){
      nodes[t,] = c(i,j-i,seats-j);
      t=t+1;
    }
  }  
  
  index=as.matrix(1:nnodes)
  
  #node labels for seats
  label=cbind(as.character(nodes[,1]),matrix("-",nnodes),as.character(nodes[,2]),matrix("-",nnodes),as.character(nodes[,3]))
  label=do.call("paste0",as.data.frame(label))
  
  
  nodes <- cbind(index,as.data.frame(nodes),label)
  names(nodes) <- c("index",letters[24:26],"label")
  return(nodes);
  
}

```

```{r, echo = F}

generateColors <- function (colorRGB, seats) {
  
  nnodes = (seats+1)*(seats+2)/2;
  nodes <- as.matrix(generateNodes(seats)[,c("x","y","z")])
  #decimal codes for colors in nodes
  Code3 = floor(nodes*255.9/seats) #255.9 avoids seats -> 256 -> HEX #100 case
  #linear transformation to fixed extreme colors
  CodeDecRGB = floor(Code3%*%matrix(colorRGB,3,3, byrow=T)/256)
  #hex codes for colors in nodes
  CodeRGB=cbind(matrix("#",nnodes),format(as.hexmode(CodeDecRGB[,1]),width=2),format(as.hexmode(CodeDecRGB[,2]),width=2),format(as.hexmode(CodeDecRGB[,3]),width=2))
  CodeRGB=do.call("paste0",as.data.frame(CodeRGB))
  values=CodeRGB
  
  return(values);
  
}

```

```{r, echo = F}

alloc <- function(parties, votes, seats, step, threshold=0){
  
  #function for the seat allocation and its ordering
  #computes allocation for several values of seats and divisor step methods
  #with the same quotiens table


  
  votes=votes*(votes>=(threshold*sum(votes)))
  
  if (sum(votes>0)==0) {
    
       votes <- votes*0+1
       #to avoid an error in the share of seats
    
  }
  
  Mst <- max(step)
  Mse <- max(seats,1) #1 to avoid 0
  nquotients=(1+Mst*(Mse-1))
  
  #table with all the quotients needed
  quotienstable <- data.frame( 
    parties    = rep(parties, each = nquotients), 
    quotients  = as.vector(sapply(votes, function(x) 
      x/seq(from=1, to=nquotients) )),
    votesrep   = rep(votes, each = nquotients), 
    #in a tie of quotiens, the party with more votes first
    tiebreak = rep(runif(length(parties)), each = nquotients) #
    #in a tie of votes, first seats allocated at random quotientsthen the nexts seats in the same order
  ) 
  
  SeatsList=list()
  filteredtable =list()
  
  
  for (j in 1:length(step)) {
    
    
    #select from the table of all quotiens the ones whose divisors
    #belong to the current sequence, given 'seats' and 'step'
    select <- rep(seq(from=1, to=1+step[j]*(Mse-1), by=step[j]),length(parties))+
      rep(seq(from=0,to=nquotients*length(parties)-1,by=nquotients),each=Mse)
    
    filteredtable [[j]] <- quotienstable$parties[select][order(-quotienstable$quotients[select], -quotienstable$votesrep[select],quotienstable$tiebreak[select])] #,runif(length(parties))
    
    SeatsList[[j]]<-list()
    
    #a vector of values for seats if you want to compute the partial sums
    for (i in 1:length(seats)){
      
      SeatsList[[j]][[i]]= table(filteredtable[[j]][1:seats[i]])
      
      if (seats[i]==0){
    
        SeatsList[[j]][[i]]=0*SeatsList[[j]][[i]]
        
    
      }

      
    }
    
    names(SeatsList[[j]])[1:length(seats)]<-do.call("paste0",as.data.frame(cbind("divisor step ",step[j]," for ", seats," seats")))
    
    
    SeatsList[[j]][[length(seats)+1]] = as.matrix(filteredtable[[j]][1:Mse]) #ordering
    
    names(SeatsList[[j]])[length(seats)+1]<-paste0("ordering for divisor step ", step[j]," for ", Mse," seats")
    
    
  }
  
  
  return(SeatsList);
  
}

```

```{r, echo = F}

generateDots <- function(dotsperside, method="lattice"){
  
  dots <- (dotsperside+1)*(dotsperside+2)/2
  
  if (method == "cartesian") {
    #Map Cartesian to Ternary to produce a homegeneous simulation
    Rc = matrix(runif(2*dots), nrow=dots, ncol=2)
    R  = matrix(apply(Rc,1, CartesianToTernary), nrow=dots, ncol=3, byrow=TRUE)
  }
  
  else if (method == "ternary") {
    #Ternary simulation. Projects points in[0,1]^3 to the sum(x)=1 hyperplane
    #This creates way more points in the center than in the extremes
    R = matrix(runif(3*dots), nrow=dots, ncol=3)
    R = prop.table(R,1) #rows sum 1
  }
  
  else if (method == "lattice") {
    #lattice of dots
    
    #read this if you want to use dots instead of dotsperside as input variable:
    #if n is dotsperside
    #dots <- (n+1)*(n+2)/2  
    #inverse calculation:
    #n <- floor((sqrt(8*dots+1)-3)/2) #exact
    #n <- floor(sqrt(2*dots)) #aprox
    
    #then redefine number of dots
    #dots <- (n+1)*(n+2)/2
    R <- matrix(0,nrow=dots, ncol=3)
    i <- 1
    for (x in 0:dotsperside){
      
      for (y in 0:(dotsperside-x)){
        
        R[i,]<- c(x,y,dotsperside-x-y)
        i <- i+1
        
      }
    }
    R = prop.table(R,1) #rows sum 1
  }
  
  return(R);
  
}

```

```{r, echo = F}

CartesianToTernary <- function (x) {
  
  #for homogeneous simulation
  #send an subset of [0,1]x[0,1] which is an equilateral triangle to the ternary diagram 
  
  while ((x[1]<=1/2 & x[2]>2*sin(pi/3)*x[1]) | (x[1]>1/2 & x[2]>2*sin(pi/3)*(1-x[1])))
    x=runif(2);
  
  v = cbind(1-x[1]-x[2]/(2*sin(pi/3)),x[2]/sin(pi/3),x[1]-x[2]/(2*sin(pi/3)));
  
  return(v);
  
}

```

```{r, echo = F}

UniformNearest <- function (x, seats, nodes, nnodes) {
  
  Uniform = which.min(apply(abs(nodes/seats - rep(1,nnodes) %*% t(x)),1,max))
  
  return(Uniform);
  
}

```

```{r, echo = F}

ManhattanNearest <- function (x, seats, nodes, nnodes) {
  
  Manhattan = which.min(apply(abs(nodes/seats - rep(1,nnodes) %*% t(x)),1,sum))
  
  return(Manhattan);
  
}

```

```{r, echo = F}

EuclidNearest <- function (x, seats, nodes, nnodes) {
  
  Euclid = which.min(apply((nodes/seats - rep(1,nnodes) %*% t(x))^2,1,sum))
  
  return(Euclid);
  
}

```

```{r, echo = F}

AllocatedNode <- function (y, nodes, nnodes) {
  
  Node = which.min(apply(abs(nodes - rep(1,nnodes) %*% t(y)),1,max))
  
  return(Node);
  
}

```

```{r, echo = F}

SpatialData <- function (dotsperside, seats, step=1, threshold=0, method="lattice") {
  
  
  #Generate random electoral results
  R <- generateDots(dotsperside, method=method)
  dots=dim(R)[1]  #dots <- (dotsperside+1)*(dotsperside+2)/2
  
  Seats=max(seats)
  
  #nodes
  nodes  <- as.matrix(generateNodes(Seats)[,c("x","y","z")])
  nnodes <- (Seats+1)*(Seats+2)/2;
  
  #Indexes for Voronoi regions
  Uniform   = apply(R, 1, UniformNearest,   seats=Seats, nodes = nodes, nnodes=nnodes)
  Manhattan = apply(R, 1, ManhattanNearest, seats=Seats, nodes = nodes, nnodes=nnodes)
  Euclid    = apply(R, 1, EuclidNearest,    seats=Seats, nodes = nodes, nnodes=nnodes)
  
  #allocate seats
  AllocStructure <- apply(R, 1, function(x) alloc(as.character(1:3), x, seats, step, threshold))
  #input a vector of values for seats of to compute partial sums
  
  df=list() #list of dataframes, one for each 'step' value
  
  #loop for diferent 'step's
  for (j in 1:length(step)){
    
    #allocation
    AllocPartial=matrix(0,dots,length(seats))
    
    for (i in 1:length(seats)){
      
      S = t(matrix(sapply(AllocStructure, function(x) x[[j]][[i]]),nrow=3,ncol=dots))
      
      nodes_sub <- as.matrix(generateNodes(seats[i])[,c("x","y","z")])
      
      AllocPartial[,i] = apply(S, 1, AllocatedNode, nodes=nodes_sub, nnodes=(seats[i]+1)*(seats[i]+2)/2)
      
    }
    
    #allocation order
    #computes allocation ordering for max(seats) in each step value
    AllocOrder = t(matrix(sapply(AllocStructure, function(x) as.integer(x[[j]][[length(seats)+1]])),nrow=Seats,ncol=dots))
    vectorOrderCode=as.matrix(3^(0:(Seats-1)))
    #this coding highlights the last seats over the first ones
    # so that there is contrast between adjacent regions
    AllocOrderCode = (matrix(AllocOrder, ncol=Seats)-1) %*% as.matrix(vectorOrderCode)
    
    dfPartial=as.data.frame(AllocPartial)
    names(dfPartial) <- do.call(paste0,as.data.frame(cbind("All",seats)))
    names(dfPartial)[which(seats==Seats)] <- "Allocated"
    
    #assembling a data frame
    df0 = data.frame(
      
      
      x             = as.matrix(R[,1]),
      y             = as.matrix(R[,2]),
      z             = as.matrix(R[,3]),
      
      Sx            = S[,1],
      Sy            = S[,2],
      Sz            = S[,3],
      
      Euclid,
      Manhattan,
      Uniform,
      
      Malapportionment = AllocPartial[1:dots,length(seats)] != Euclid[1:dots],
      
      AllocOrderCode
      
      
    )
    
    df0=cbind(df0,dfPartial)
    
    df[[j]]<-df0
    
  } #end of loop for different 'step's
  
  
  return(df);
  
}

```

```{r, echo = F}

generateOrderColors <- function (colorRGB, seats, validCodes=TRUE) {
  
  #generate order color from alloc order codes
  
  #extract allocation order from allocation order codes:
  OrderCode <-as.matrix(0:(3^seats-1))
  
  OrderRests <- t(matrix(apply(OrderCode, 1, function(x) x %% (3^(1:seats))),ncol=3^seats, nrow=seats))
  #(this is vectorial for OrderRests <- OrderCode %% (3^(1:seats))  )
  
  Order_from_code <- (cbind(OrderRests,0)-cbind(0,OrderRests))[,1:seats]/t(matrix(rep(3^(0:(seats-1)),3^seats),ncol=3^seats,nrow=seats))+1
  vectorOrderCode3 <- 2^(0:(seats-1))
  #decimal codes for colors in nodes
  Code3 = cbind((Order_from_code == 1)%*%as.matrix(vectorOrderCode3),
                (Order_from_code == 2)%*%as.matrix(vectorOrderCode3),
                (Order_from_code == 3)%*%as.matrix(vectorOrderCode3))
  
  #linear transformation to fixed extreme colors
  CodeDecRGB = floor(Code3%*%matrix(colorRGB,3,3, byrow=T)/2^seats)
  
  #hex codes for colors in nodes
  CodeRGB = cbind(matrix("#",3^seats),format(as.hexmode(CodeDecRGB[,1]),width=2),format(as.hexmode(CodeDecRGB[,2]),width=2),format(as.hexmode(CodeDecRGB[,3]),width=2))
  CodeRGB = do.call("paste0",as.data.frame(CodeRGB))
  
  #values = CodeRGB[validCodes]
  values = CodeRGB[c(validCodes, 3^seats)] #added one more color bc scale_color_manual() demanded one more color
  #values = CodeRGB[c(1, validCodes)] #added one more color bc scale_color_manual() demanded one more color
  
  
  return(values);
  
}

```

```{r, echo = F}

generateHexagonData <- function(seats, step=1) {
  
  divisor <- seq(from=1, to=1+step*(seats+2-1), by=step)
  divisor <- c(0,divisor)
  
  NodesData <- generateNodes(seats)
  
  hexagon <- matrix(0,nrow=(seats+1)*(seats+2)/2, ncol=6*3)
  
  for (i in 1:((seats+1)*(seats+2)/2)){
    
    n <- NodesData[i,2:4] #node
    hexagon[i,] <- rep(c(n[[1]],n[[2]],n[[3]]),6)+c(1,0,0, 1,0,1, 0,0,1, 0,1,1, 0,1,0, 1,1,0)
    hexagon[i,] <- divisor[hexagon[i,]+1]
    
  }
  
  dhex <- as.data.frame(cbind(rep(1:((seats+1)*(seats+2)/2),each=6), matrix(t(hexagon),nrow=6*(seats+1)*(seats+2)/2, ncol=3, byrow=T),
                              rep(NodesData$x,each=6),rep(NodesData$y,each=6),rep(NodesData$z,each=6)))
  
  names(dhex) <- c('hex','x','y','z','nx','ny','nz')
  
  return(dhex)
  
}

```

```{r, echo = F}

generatelabels <- function(seats, step=1){
  
  #labels for the center of the regions
  
  nnodes     <- (seats+1)*(seats+2)/2
  nodes      <- generateNodes(seats)
  dhex       <- generateHexagonData(seats, step=step)
  labelsData <- as.data.frame(matrix(0,nnodes, 5))
  
  for (index in 1:nnodes) {
    
    labelsData[index,1]   <- as.integer(index)
    labelsData[index,2:4] <- as.numeric(t(colSums(dhex[dhex$hex==index,2:4])))
    labelsData[index,5]   <- toString(nodes[index,5])
    
  }
  
  names(labelsData) <- c("index","x","y","z","label")
  
  return(labelsData)
  
}

```

```{r, echo = F}

plotallocation <- function (seats, step=1, colorRGB0=c(242,74,87, 124,218,198, 2,114,195), alpha=0.75, labelsize=4, dotsize=1, dotcolor='khaki2') {
  
  NodesData <- generateNodes(seats)
  dhex <- generateHexagonData(seats, step)
  labelsData <- generatelabels(seats, step)
  
  polygons <- ggtern(data=dhex, aes(x, y, z)) + theme_nomask()
  
  for (i in 1:((seats+1)*(seats+2)/2)){
    
    polygons <- polygons + geom_polygon(aes(fill=hex, group=hex), data=dhex[dhex==i,] , fill=generateColors(colorRGB0,seats)[i], colour='grey40', size=0, alpha=alpha) #no lines
    
  }
  
  polygons <- polygons + geom_point(data=NodesData,aes(x,y),color=dotcolor, size=dotsize)+
    #geom_text(data=NodesData, aes(label=label), color="grey30", hjust=0.5, vjust=-0.6, size=4)+ 
    labs(x="X",y="Y",z="Z",title="")
  
  polygons <- polygons + #geom_point(data=labelsData,aes(x,y,z),color="khaki2")+
    geom_text(data=labelsData, aes(label=label), color="grey30", hjust=0.5, vjust=0.5, size=labelsize)+ 
    labs(x="X",y="Y",z="Z",title="")
  
  return(polygons)
  
}

```

```{r, echo=FALSE}
inputPanel(
  
  #radioButtons("step", label = "Number of steps:", 1:3, selected=1, inline=T),
  
  radioButtons("electmethod", label = "Electoral method:", c("D'Hondt","Sainte-Lague", "Danish"), selected="D'Hondt", inline=F),
  
  sliderInput("seats", label = "Number of seats:",
              min = 1, max = 25, value = 5, step = 1)
  
)

inputPanel(
  
  checkboxGroupInput("ChoosePlots", "Choose simulations:",
                   c("Theoretical Allocation" = "TQp",
                     "Allocation (sim.)" = "Qp",
                     "Malapportionment (sim.)" = "Mp",
                     "Voronoi-Hare (sim.)" = "Vp",
                     "Ordering (sim.)" = "Op"), selected = "TQp"),
  
  selectInput("method", label = "Dot distribution (only sim.):",
              choices = c("lattice","cartesian","ternary"), selected = "lattice"),
  
  sliderInput("threshold", label = "Threshold (only simulation):",
              min = 0, max = .30, value = 0, step = .01),
  
  sliderInput("dotsperside", label = "Dot density (only sim; set to min if not used):",
              min = 10, max = 300, value = 10, step = 10)

)
  
inputPanel(
  
  selectInput("color1", label = "Color 1:",
              choices = c('red','green','blue','yellow','magenta','cyan','purple','brown','orange','antiquewhite','aquamarine3','azure1','brown3','brown4','burlywood4','cadetblue','coral3','cornsilk','cornsilk2','cyan3','darkcyan','darkolivegreen4','darkorange2','darkred','darkslategray','darkseagreen','darksalmon','darkslategray3','deeppink4','dodgerblue3','darkorchid2','dodgerblue4','firebrick3','floralwhite','honeydew3','hotpink4','khaki3','khaki4','lavenderblush3','lightblue3','lightcyan2','lightpink2','lightsalmon2','lightsteelblue3','lightyellow1','indianred3','indianred4','ivory','ivory3','midnightblue','mintcream','mistyrose2','navajowhite1','orangered4','paleturquoise2','palegreen3','rosybrown2','royalblue3','salmon','seagreen','seashell1','sienna2','turquoise3','wheat2','black','gray10','gray30','gray50','gray70','gray90','white'), selected = 'indianred3'),
  
  selectInput("color2", label = "Color 2:",
              choices = c('red','green','blue','yellow','magenta','cyan','purple','brown','orange','antiquewhite','aquamarine3','azure1','brown3','brown4','burlywood4','cadetblue','coral3','cornsilk','cornsilk2','cyan3','darkcyan','darkolivegreen4','darkorange2','darkred','darkslategray','darkseagreen','darksalmon','darkslategray3','deeppink4','dodgerblue3','darkorchid2','dodgerblue4','firebrick3','floralwhite','honeydew3','hotpink4','khaki3','khaki4','lavenderblush3','lightblue3','lightcyan2','lightpink2','lightsalmon2','lightsteelblue3','lightyellow1','indianred3','indianred4','ivory','ivory3','midnightblue','mintcream','mistyrose2','navajowhite1','orangered4','paleturquoise2','palegreen3','rosybrown2','royalblue3','salmon','seagreen','seashell1','sienna2','turquoise3','wheat2','black','gray10','gray30','gray50','gray70','gray90','white'), selected = 'aquamarine3'),
  
  selectInput("color3", label = "Color 3:",
              choices = c('red','green','blue','yellow','magenta','cyan','purple','brown','orange','antiquewhite','aquamarine3','azure1','brown3','brown4','burlywood4','cadetblue','coral3','cornsilk','cornsilk2','cyan3','darkcyan','darkolivegreen4','darkorange2','darkred','darkslategray','darkseagreen','darksalmon','darkslategray3','deeppink4','dodgerblue3','darkorchid2','dodgerblue4','firebrick3','floralwhite','honeydew3','hotpink4','khaki3','khaki4','lavenderblush3','lightblue3','lightcyan2','lightpink2','lightsalmon2','lightsteelblue3','lightyellow1','indianred3','indianred4','ivory','ivory3','midnightblue','mintcream','mistyrose2','navajowhite1','orangered4','paleturquoise2','palegreen3','rosybrown2','royalblue3','salmon','seagreen','seashell1','sienna2','turquoise3','wheat2','black','gray10','gray30','gray50','gray70','gray90','white'), selected = 'royalblue3'),
  
  sliderInput("Opacity", label = "Opacity:",
              min = 0, max = 1, value = .8, step = .1)
  
)


inputPanel(
  
  numericInput("votes1", label="Votes for Party X", value=0, min = 0),
  numericInput("votes2", label="Votes for Party Y", value=0, min = 0),
  numericInput("votes3", label="Votes for Party Z", value=0, min = 0)
  
)


renderPlot({

  dots <- (input$dotsperside+1)*(input$dotsperside+2)/2
  
  colorRGB0 <- matrix(rbind(col2rgb(input$color1),
                            col2rgb(input$color2),
                            col2rgb(input$color3)),1,9)
  
  #step <- as.integer(input$step)
  
  if (input$electmethod == "D'Hondt"){
    
    step <- 1
    
  } else if (input$electmethod == "Sainte-Lague"){
    
    step <- 2
    
  } else if (input$electmethod == "Danish"){
    
    step <- 3
    
  }
  
  
  
  TQp <- plotallocation(input$seats, step=step, colorRGB0=colorRGB0, alpha=input$Opacity)
  
  
   NodesData <- generateNodes(input$seats)
     
  df = SpatialData(dotsperside=input$dotsperside-1, seats=input$seats, step=step, threshold=input$threshold, method=input$method)
  
  votes <- as.data.frame(cbind(0,0,0))
  votesinput <- as.data.frame(cbind(input$votes1,input$votes2,input$votes3))
  names(votes) <- c("x","y","z")
  names(votesinput) <- c("x","y","z")
  
  if (max(votesinput)>0 & is.na(min(votesinput))==F) {
  
  votes <- votesinput
    
  allocated <- alloc(letters[24:26], unlist(votes), input$seats, step, input$threshold)
  
  nodes  <- as.matrix(NodesData[,c("x","y","z")])
  nnodes <- (input$seats+1)*(input$seats+2)/2
  
  index <- AllocatedNode(allocated[[1]][[1]], nodes, nnodes)
  
  dhex <- generateHexagonData(input$seats, step=step)
  
  labelcoords <- as.data.frame(t(colSums(dhex[dhex$hex==index,2:4])))
  labelcoords <- cbind(labelcoords,NodesData[index,]$label)
  names(labelcoords)[4] <- "label"
  
  
  TQp <- TQp + geom_polygon(aes(fill=hex, group=hex), data=dhex[dhex==index,] , fill=generateColors(colorRGB0,input$seats)[index], colour='grey20', size=1, alpha=0.85) +
               geom_point(data=votes ,aes(x,y),color="grey20", size=4, alpha=.8)+
               geom_text(data=labelcoords,aes(label=label), color="grey15", hjust=0.5, vjust=0.5, size=6)+
               geom_point(data=NodesData[index,],aes(x,y),color="khaki2")
  
  }
  
  Qp <- ggtern(data=df[[1]],aes(x,y,z,color=as.factor(Allocated)))+
  #theme_bw()+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_point(alpha=input$Opacity)+
  geom_point(data=NodesData,aes(x,y),color="khaki2")+
  geom_text(data=NodesData,aes(label=label), color="grey30", hjust=0.5, vjust=-0.6, size=4)+ 
  labs(x="X",y="Y",z="Z",title="Quotients Allocation")+
  #scale_colour_grey(start = 0.4, end = 1, na.value = "black", guide = FALSE)
  scale_colour_manual(values=generateColors(colorRGB0,input$seats),guide=FALSE,na.value="khaki2")
  
  Mp <- ggtern(data=df[[1]],aes(x,y,z,color=Malapportionment)) +
  #theme_rgbw() +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_point(alpha=0.8) +
  geom_point(data=NodesData,aes(x,y),alpha=0.8,color="grey60")+
  labs(x="X",y="Y",z="Z",title="Malapportionment")+
  #scale_colour_grey(na.value = "black", guide = FALSE)
  scale_colour_brewer(palette = "YlGnBu", na.value = "grey60", guide = FALSE)
  
  Vp <- ggtern(data=df[[1]],aes(x,y,z,color=as.factor(Manhattan)))+
  #theme_bw()+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_point(alpha=1)+
  geom_point(data=NodesData,aes(x,y),color="khaki2")+
  geom_text(data=NodesData,aes(label=label), color="grey30", hjust=0.5, vjust=-0.6, size=4)+ 
  labs(x="X",y="Y",z="Z",title="Voronoi Allocation")+
  #scale_colour_grey(start = 0.4, end = 1, na.value = "black", guide = FALSE)
  scale_colour_manual(values=generateColors(colorRGB0,input$seats), guide=FALSE, na.value="khaki2")
  
  Op <- ggtern(data=df[[1]],aes(x,y,z,color=as.factor(AllocOrderCode))) +
  #theme_bw()+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_point(alpha=1) +
  geom_point(data=NodesData,aes(x,y),color="khaki2")+
  labs(x="X",y="Y",z="Z",title="Allocation Ordering")+
  scale_colour_manual(values=
      generateOrderColors(colorRGB0,input$seats,sort(unique(df[[1]]$AllocOrderCode))),guide=FALSE, na.value="khaki2")
  
  
  plist=list(TQp,Qp,Mp,Vp,Op)
  names(plist) <- c("TQp","Qp","Mp","Vp","Op")
  #ggtern.multi(plotlist=plist[input$ChoosePlots], cols=length(input$ChoosePlots))
  #ggtern.multi(plotlist=plist[input$ChoosePlots], cols=2)
  grid.arrange(grobs = plist[input$ChoosePlots], ncol=2)
    
  
}, width=3600, height=2800, res=288)

#renderPlot({


#size of the regions # 1 ~= dots/nnodes
#nnodes=(input$seats+1)*(input$seats+2)/2;
#RegionSizeQ  = table(df[[1]]$Allocated[1:dots])/(dots/nnodes)
#RegionSizeV  = table(df[[1]]$Manhattan[1:dots])/(dots/nnodes)

  
#par(mfrow=c(3,1))
#plot(RegionSizeQ, main="Quotients region sizes")
#plot(RegionSizeV, main="Voronoi region sizes" )
#par(mfrow=c(1,1))


#points not allocated by the quotients method in their corresponding Voronoi region
#sum(df[[1]]$Malapportionment[1:dots])/dots
  

  
#})

```


